name: Generate Pacman

on:
  schedule:
    - cron: "0 0 * * *" # araw-araw mag-update
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Pacman
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: jvhluces
          outputs: dist/github-contribution-grid-pacman.svg
          color_snake: "#FFD700"   # Pac-Man yellow
          color_dots: "#1E1E2F"    # dark background
          color_empty: "#2A2A40"   # subtle grid tone

      - name: Push Pacman to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
          target_branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
